language: generic

branches:
  only:
    - master

deploy:
  provider: heroku
  api_key:
    secure: WpJ3DzXgpFQ6bSwkS4QrrUlDk9JVoYgEUgYvOfN6y6aUOoYlJuErOU+6MRyLPQRkKquNGUxpVOKWU06OOmLpstjTfi6BTEH9da3IFuke8Sd3+HELYJF0A3Ae4amtMK9Ak7bsY8G75Zy9zE0RcLrAknRAu4aGi7X5F63mEyrZ0XH/lrESpD3e8RdCUR3F88jVtKuwYY7yG0K/qknJYHEpxhjqaDi9pLzXZsjddzFDM1wTFTbAXe7DIaJ6KtrCk+8UxKNHucrRakbXoE9CNFoRVJT5B8cWC+DdFw1bikKbE6IEA7R8cwZDE0Uo+gcl3I4c1c23247IeW0QMk3vrxAb0F8egCqGSK+QlSfi1pWDiRb9inVgU4LVA3i2GVHdrLsLh8p3Q0pjklJjOtfI0vyweiJJrZO0aL9IpwTUYx7hiDg9eiGAxIXV9XiBectfb0+6Kl9xxRVmh8QuX5hECC7o+YPXzOHZnPexb/XRc3O+yZX+XDGyzUC01eR8gOK/LRkT2ryKeXTxyrMMWLd3Wh1U+NF5Z532K9ZJQrldhty4/ErDRBaR5WEeQYfkN2lf9sKivulX1Xej2k0WgQA7SD3IxT0KL6Jk1aIjOEmNhqQIYgWNgq9pyrZ7/eCe/8sli1Yv24NCMDUi3oY93rUC9wO0hPjy9pIVJMSnCueRaB19Bns=
  on: master
